

import 'package:buecherteam_2023_desktop/Data/book.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  late List<Book> sampleBooks;
  setUp(() {
    sampleBooks = [
      Book(
        bookId: '1',
        name: 'Algebra Basics',
        subject: 'Math',
        classLevel: 5,
        trainingDirection: ['STEM'],
        amountInStudentOwnership: 10,
        nowAvailable: 5,
        totalAvailable: 15,
        isbnNumber: '1234567890',
        publisher: 'SchoolBooks Inc.',
        price: '15.99',
        admissionNumber: 'ADM123',
      ),
      Book(
        bookId: '2',
        name: 'History of Rome',
        subject: 'History',
        classLevel: 6,
        trainingDirection: ['Humanities'],
        amountInStudentOwnership: 8,
        nowAvailable: 2,
        totalAvailable: 10,
        isbnNumber: null,
        publisher: null,
        price: null,
        admissionNumber: null,
      ),
      Book(
        bookId: '3',
        name: 'Advanced Biology',
        subject: 'Biology',
        classLevel: 10,
        trainingDirection: ['Science'],
        amountInStudentOwnership: 12,
        nowAvailable: 6,
        totalAvailable: 18,
        isbnNumber: '9876543210',
        publisher: 'EduScience',
        price: '21.00',
        admissionNumber: 'ADM321',
      ),
      Book(
        bookId: '4',
        name: 'World Geography',
        subject: 'Geography',
        classLevel: 8,
        trainingDirection: ['Humanities'],
        amountInStudentOwnership: 6,
        nowAvailable: 4,
        totalAvailable: 10,
        isbnNumber: '1122334455',
        publisher: 'GeoBooks',
        price: '17.50',
        admissionNumber: 'ADM789',
      ),
      Book(
        bookId: '5',
        name: 'Physics Fundamentals',
        subject: 'Physics',
        classLevel: 9,
        trainingDirection: ['STEM'],
        amountInStudentOwnership: 9,
        nowAvailable: 3,
        totalAvailable: 12,
        isbnNumber: '5566778899',
        publisher: 'SciPress',
        price: '18.75',
        admissionNumber: 'ADM654',
      ),
      Book(
        bookId: '6',
        name: 'Literary Classics',
        subject: 'Literature',
        classLevel: 7,
        trainingDirection: ['Humanities'],
        amountInStudentOwnership: 5,
        nowAvailable: 2,
        totalAvailable: 7,
        isbnNumber: null,
        publisher: null,
        price: null,
        admissionNumber: null,
      ),
      Book(
        bookId: '7',
        name: 'Chemistry 101',
        subject: 'Chemistry',
        classLevel: 10,
        trainingDirection: ['Science'],
        amountInStudentOwnership: 7,
        nowAvailable: 5,
        totalAvailable: 12,
        isbnNumber: '9988776655',
        publisher: 'ChemPub',
        price: '19.90',
        admissionNumber: 'ADM987',
      ),
      Book(
        bookId: '8',
        name: 'French for Beginners',
        subject: 'French',
        classLevel: 6,
        trainingDirection: ['Languages'],
        amountInStudentOwnership: 3,
        nowAvailable: 1,
        totalAvailable: 4,
        isbnNumber: null,
        publisher: 'LangBooks',
        price: '12.00',
        admissionNumber: null,
      ),
      Book(
        bookId: '9',
        name: 'Basic Computing',
        subject: 'IT',
        classLevel: 7,
        trainingDirection: ['STEM'],
        amountInStudentOwnership: 6,
        nowAvailable: 6,
        totalAvailable: 12,
        isbnNumber: '7777888899',
        publisher: 'TechPress',
        price: '22.50',
        admissionNumber: 'ADM556',
      ),
      Book(
        bookId: '10',
        name: 'Economics Principles',
        subject: 'Economics',
        classLevel: 9,
        trainingDirection: ['Business'],
        amountInStudentOwnership: 4,
        nowAvailable: 2,
        totalAvailable: 6,
        isbnNumber: '3344556677',
        publisher: 'BizBooks',
        price: '16.25',
        admissionNumber: 'ADM432',
      ),
      Book(
        bookId: '11',
        name: 'Introduction to Music',
        subject: 'Music',
        classLevel: 5,
        trainingDirection: ['Arts'],
        amountInStudentOwnership: 2,
        nowAvailable: 2,
        totalAvailable: 4,
        isbnNumber: null,
        publisher: null,
        price: null,
        admissionNumber: null,
      ),
      Book(
        bookId: '12',
        name: 'Environmental Science',
        subject: 'Science',
        classLevel: 8,
        trainingDirection: ['Science'],
        amountInStudentOwnership: 11,
        nowAvailable: 6,
        totalAvailable: 17,
        isbnNumber: '2233445566',
        publisher: 'NatureBooks',
        price: '20.00',
        admissionNumber: 'ADM678',
      ),
      Book(
        bookId: '13',
        name: 'Art Techniques',
        subject: 'Art',
        classLevel: 6,
        trainingDirection: ['Arts'],
        amountInStudentOwnership: 1,
        nowAvailable: 0,
        totalAvailable: 1,
        isbnNumber: null,
        publisher: null,
        price: null,
        admissionNumber: null,
      ),
      Book(
        bookId: '14',
        name: 'German Grammar',
        subject: 'German',
        classLevel: 7,
        trainingDirection: ['Languages'],
        amountInStudentOwnership: 4,
        nowAvailable: 2,
        totalAvailable: 6,
        isbnNumber: '6677889900',
        publisher: 'LangBooks',
        price: '14.30',
        admissionNumber: 'ADM765',
      ),
      Book(
        bookId: '15',
        name: 'Geometry Advanced',
        subject: 'Math',
        classLevel: 5,
        trainingDirection: ['STEM'],
        amountInStudentOwnership: 6,
        nowAvailable: 2,
        totalAvailable: 8,
        isbnNumber: '1111222233',
        publisher: 'SchoolBooks Inc.',
        price: '16.80',
        admissionNumber: 'ADM111',
      ),
    ];
  });
  group('getExcelBookList', () {


  });
}