version: "3.7"

services:
  couchbase-server:
    image: couchbase:community-7.2.0
    ports:
      - 8091-8097:8091-8097
      - 11210:11210
    networks:
      - couchbase-network
    ulimits:
      nofile:
        soft: 200000
        hard: 200000
      nproc: 10000

  sync-gateway:
    image: couchbase/sync-gateway:3.1.0-community
    ports:
      - 4984:4984
      - 4985:4985
    networks:
      - couchbase-network
    ulimits:
      nofile:
        soft: 200000
        hard: 200000
      nproc: 10000
    volumes:
      - ./sync-gateway-config.json:/tmp/sync-gateway-config.json
    command: ['/tmp/sync-gateway-config.json']

networks:
  couchbase-network:
    driver: bridge
