name: Build and Release Flutter App

on:
  push:
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      # Setup Flutter SDK version 3.22.0
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore File
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/keystore.jks

      - name: Decode Keystore Credentials
        run: |
          echo "${{ secrets.KEYSTORE_ALIAS }}" | base64 --decode > keystore_alias.txt
          echo "${{ secrets.KEYSTORE_PASSWORD }}" | base64 --decode > keystore_password.txt
          echo "${{ secrets.KEY_PASSWORD }}" | base64 --decode > key_password.txt

      - name: Build Signed APK
        run: |
          flutter build apk --release \
            --dart-define=KEYSTORE_PATH=android/app/keystore.jks \
            --dart-define=KEYSTORE_ALIAS=$(cat keystore_alias.txt) \
            --dart-define=KEYSTORE_PASSWORD=$(cat keystore_password.txt) \
            --dart-define=KEY_PASSWORD=$(cat key_password.txt)

  
