name: Flutter CI/CD Release Workflow

# This workflow is triggered on pushes to the repository that include a tag matching 'v*.*.*'
on:
  push:
    tags:
      - 'v*.*.*'

# Sets the permissions for the GITHUB_TOKEN to allow creating releases.
permissions:
  contents: write

jobs:
  # Job to build the Flutter application for Windows
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows executable
        run: flutter build windows

      - name: Package Windows build
        run: Compress-Archive -Path build/windows/x64/runner/Release -DestinationPath buecherteam_2023_desktop-windows.zip

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: buecherteam_2023_desktop-windows.zip

  # Job to build the Flutter application for Linux
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Linux build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libsecret-1-dev

      - name: Install dependencies
        run: flutter pub get

      - name: Build Linux executable
        run: flutter build linux

      - name: Package Linux build
        # The output is inside the 'bundle' directory
        run: zip -r buecherteam_2023_desktop-linux.zip build/linux/x64/release/bundle

      - name: Upload Linux build artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: buecherteam_2023_desktop-linux.zip

  # Job to create a GitHub Release and upload the build artifacts
  create-release:
    # This job depends on the successful completion of the build jobs
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          # The release will be created with the tag that triggered the workflow
          tag_name: ${{ github.ref_name }}
          # Attach both the Windows and Linux zip files to the release
          files: |
            artifacts/windows-build/buecherteam_2023_desktop-windows.zip
            artifacts/linux-build/buecherteam_2023_desktop-linux.zip
